import CONFIG from '../../config'
// API URL
export const API_URL = `${CONFIG.CHEF_SERVER.host}:${CONFIG.CHEF_SERVER.port}`

// Auth Actions
export const USERS_LOGIN_REQUEST = 'USERS_LOGIN_REQUEST'
export const USERS_LOGIN_SUCCESS = 'USERS_LOGIN_SUCCESS'
export const USERS_LOGIN_FAILURE = 'USERS_LOGIN_FAILURE'

// Developer Actions
export const FETCH_DEVELOPERS_BEGIN = 'FETCH_DEVELOPERS_BEGIN'
export const FETCH_DEVELOPERS_SUCCESS = 'FETCH_DEVELOPERS_SUCCESS'
export const FETCH_DEVELOPERS_FAILURE = 'FETCH_DEVELOPERS_FAILURE'

// MicroApp Actions
export const FETCH_MICROAPPS_BEGIN = 'FETCH_MICROAPPS_BEGIN'
export const FETCH_MICROAPPS_SUCCESS = 'FETCH_MICROAPPS_SUCCESS'
export const FETCH_MICROAPPS_FAILURE = 'FETCH_MICROAPPS_FAILURE'
export const DELETE_MICROAPPS_SUCCESS = 'DELETE_MICROAPPS_SUCCESS'
export const DELETE_MICROAPPS_FAILURE = 'DELETE_MICROAPPS_FAILURE'

// MicroAppBundle Actions
export const FETCH_MICROAPPBUNDLES_BEGIN = 'FETCH_MICROAPPBUNDLES_BEGIN'
export const FETCH_MICROAPPBUNDLES_SUCCESS = 'FETCH_MICROAPPBUNDLES_SUCCESS'
export const FETCH_MICROAPPBUNDLES_FAILURE = 'FETCH_MICROAPPBUNDLES_FAILURE'
export const DELETE_MICROAPPBUNDLES_SUCCESS = 'DELETE_MICROAPPBUNDLES_SUCCESS'
export const DELETE_MICROAPPBUNDLES_FAILURE = 'DELETE_MICROAPPBUNDLES_FAILURE'
export const UPDATE_MICROAPPBUNDLES_STATUS = 'UPDATE_MICROAPPBUNDLES_STATUS'

// Modal Actions
export const OPEN_MODAL = 'OPEN_MODAL'

// Actions
export const AUTH_ACTIONS = {
  USERS_LOGIN_REQUEST,
  USERS_LOGIN_SUCCESS,
  USERS_LOGIN_FAILURE
}

export const DEVELOPER_ACTIONS = {
  FETCH_DEVELOPERS_BEGIN,
  FETCH_DEVELOPERS_SUCCESS,
  FETCH_DEVELOPERS_FAILURE
}

export const MICROAPP_ACTIONS = {
  FETCH_MICROAPPS_BEGIN,
  FETCH_MICROAPPS_SUCCESS,
  FETCH_MICROAPPS_FAILURE,
  DELETE_MICROAPPS_SUCCESS,
  FETCH_MICROAPPBUNDLES_FAILURE,
}

export const MICROAPPBUNDLE_ACTIONS = {
  FETCH_MICROAPPBUNDLES_BEGIN,
  FETCH_MICROAPPBUNDLES_SUCCESS,
  FETCH_MICROAPPBUNDLES_FAILURE,
  DELETE_MICROAPPBUNDLES_SUCCESS,
  DELETE_MICROAPPBUNDLES_FAILURE,
  UPDATE_MICROAPPBUNDLES_STATUS
}

export const MODAL_ACTIONS = {
  OPEN_MODAL
}